### PR TITLE
Add -version flag

### LINKED ISSUE #7: Add --version flag
Each command should support `--version` to output it's version.

### PR DESCRIPTION
**Pull request by rothgar**
I'm open to suggestions on defaults for version and commit.
goreleaser will automatically add flags
```
-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
```

We can customize it if we want.

fixes #7

### CODE REVIEW

**Comment by rothgar** [comment]
Link to goreleaser doc
https://goreleaser.com/customization/#Builds

**Comment by sendqueery** [comment]
Does this PR need to update .goreleaser.yml as well?

**Comment by rothgar** [comment]
No updated needed because `main.version` is already part of the default goreleaser build flags

**Comment by sendqueery** [comment]
LGTM!

**Pull request merged**
